### ISSUE TITLE
Set resource attributes correctly

### ISSUE THREAD

**Issue by jcchavezs** [hypertrace/pythonagent#152]
We need to override default values coming from opentelemetry libraries.

telemetry.sdk.version should be the version of our library
telemetry.sdk.name should be hypertrace

![image](https://user-images.githubusercontent.com/3075074/116123801-bfb3d780-a6c3-11eb-9cec-1e98a238aef1.png)

**Comment by rcbjBlueMars** [comment]
Let's also add to the scope of this ticket correctly setting resource_attributes from agent-config.yaml.
